### ISSUE TITLE
Timeout on the Lambdas leave no log about the problem

### ISSUE THREAD

**Issue by luislhl** [HathorNetwork/hathor-explorer-service#133]
We got some timeouts from the Lambda `node_api_get_transaction`. When a timeout happens in the Lambda, we have no way to know what exactly happened.

To improve this, we should configure a timeout in the client that is lesser than the Lambda timeout, so it times out earlier and logs something about the error.

**Comment by alexruzenhack** [comment]
The AWS Lambda Function timeout is configured by default with 6 seconds in Serverless. That said, the client should have timeout of 5 seconds.
